spring.application.name=gateway-service
server.port=8080
spring.cloud.gateway.routes[0].id=mission-service
spring.cloud.gateway.routes[0].uri=http://mission-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/missions/**

spring.cloud.gateway.routes[1].id=telemetry-service
spring.cloud.gateway.routes[1].uri=http://telemetry-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/telemetry/**

management.endpoints.web.exposure.include=health